### ISSUE TITLE
Not compatible with Firefox Quantum

### ISSUE THREAD

**Issue by suterma** [jhartz/copy-url-with-hash#5]
In the Firefox Add-ons repository, the extension is reported as "Not compatible with Firefox Quantum". Do you plan to upgrade your extension?

It would be very handy, and this one is the only one I found that offers this kind of functionality.

**Comment by jhartz** [comment]
Yeah, I'm planning to upgrade it to use the new WebExtension API's at some point, hopefully soon when I get some time.

Thanks for the interest! I'll keep this thread updated.

**Comment by jhartz** [comment]
I submitted the webextension version (version 2.0.0) to AMO, and they approved it: https://addons.mozilla.org/en-US/firefox/addon/copy-url-with-hash/

Unfortunately, it doesn't work with Firefox for Android, but that's due to missing webextension APIs on that platform, so unfortunately there's nothing I can do about that now.

Since it's working again on desktop Firefox, though, I'm going to close this out. If you find any bugs in the new version, feel free to open a new issue.
